### ISSUE TITLE
More details or photos of jumpers?

### ISSUE THREAD

**Issue by loopj** [drewtenn/ookdump#1]
Hey @drewtenn this looks super interesting, was wondering if you could share more details about which pins you attached the jumpers to, I can't figure it out from your README.

Thanks in advance

**Comment by drewtenn** [comment]
I used the Feather M0 RFM69 433 MHz module. You'll see an IO1 and IO2 pin near the RFM radio module. I hooked them up to pin 10 and 11 on the board. One of the pins fires an interrupt on a rising edge and the other is the data line.

I used this to capture timings for my Somfy RTS remote so that I could emulate the remote. I used Homespan to use it through HomeKit on my iOS devices.

Here's the pin out of the board I used. Don't use the Lora but rather the RFM 433 board.

https://learn.adafruit.com/adafruit-feather-m0-radio-with-rfm69-packet-radio/pinouts

**Comment by loopj** [comment]
Thanks, this helped me figure it out!
